# Generated by Django 3.1.5 on 2021-01-27 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('npc', models.CharField(choices=[('HOBIN', 'HOBIN'), ('HAECHEOL', 'HAECHEOL'), ('YOONHO', 'YOONHO'), ('CHANI', 'CHANI'), ('GANGWOOK', 'GANGWOOK')], default='HOBIN', max_length=20)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='problems.problem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
